### ISSUE TITLE
Change Command line options to AmigaDOS style

### ISSUE THREAD

**Issue by bubbob42** [Arisamiga/Mnemosyne#18]
Thank you for the update!

Regarding the „-g“ option for CLI — that’s unix CLI style. For AmigaDOS, one should parse arguments  using ReadArgs(). In this case, the template would be e.g. :

G=GUI/S

And would be called with

Mnemosyne gui

or just

Mnemosyne g

Check out Autodocs for dos/ReadArgs()

**Comment by Arisamiga** [comment]
Hello! Thanks for making an issue.

The -g option was changed with the following pull request https://github.com/Arisamiga/Mnemosyne/pull/17 and was included in the latest **1.2.0** update to use the GUI Keyword.

You should be able to do `Mnemosyne GUI <path>` in the latest version of Mnemosyne.

**Comment by bubbob42** [comment]
Ahhh... I was confused by the Wiki-documentation, which still shows "-g" option. Thanks!

**Comment by Arisamiga** [comment]
> Ahhh... I was confused by the Wiki-documentation, which still shows "-g" option. Thanks!

Oh, I forgot to change that. Thanks for letting me know! (It should be changed now)

I will be closing this issue as it is resolved! If you have any further issues don't hesitate to reopen it.
