### ISSUE TITLE
Some subdir sizes won't get rounded

### ISSUE THREAD

**Issue by bubbob42** [Arisamiga/Mnemosyne#8]
Some values won't get rounded

<img width="315" alt="Mnemosyne_round" src="https://github.com/Arisamiga/Mnemosyne/assets/16854409/83685bdd-a1dd-456d-b468-ff5ec9b0bc27">

**Comment by Arisamiga** [comment]
Thanks for submitting a Issue :D

This is expected behaviour as I have outlined in this post https://eab.abime.net/showpost.php?p=1650981&postcount=9 

```
Yea, that is correct. 
Mnemosyne doesn't change to a higher format (KB,MB,GB) unless the number is so big it causes an overflow. 
That shouldn't affect the sorting tho. It keeps it more accurate 
```

**Comment by Arisamiga** [comment]
I will close this issue. If you have any further problems don't hesitate to reopen it :D
